### ISSUE TITLE
Looking forward to your code!

### ISSUE THREAD

**Issue by thaoshibe** [chufengxiao/SketchHairSalon#1]
Hi there,
I am impressed by your work!
Could you provide a rough timeline on when will the code be released?

**Comment by chufengxiao** [comment]
Hi, thanks for your attention. Sorry for late reply. Recently I am very busy with some deadlines, but I will try to make the code released in Feb 2022.

**Comment by chufengxiao** [comment]
@thaoshibe Hi, I just released the code, thanks!
