### ISSUE TITLE
cannt waiting for you code

### ISSUE THREAD

**Issue by yzy5768** [chufengxiao/SketchHairSalon#2]

**Comment by chufengxiao** [comment]
Hi, thanks for your attention. Sorry for late reply. Recently I am very busy with some deadlines, but I will try to make the code released in Feb 2022.

**Comment by ofirkris** [comment]
Hello, release still planned for this Feb?

**Comment by chufengxiao** [comment]
> Hello, release still planned for this Feb?

Hi, I just release the code, thanks!
